# settings for cross-compiling from .deb-based environment
[target.aarch64-unknown-linux-gnu]
# install gcc-aarch64-linux-gnu
linker = "aarch64-linux-gnu-gcc"

[target.x86_64-pc-windows-gnullvm]
# install binutils-mingw-w64-x86-64-ucrt mingw-w64-ucrt64-dev
# get libunwind.a static lib, like extract it from https://mirror.msys2.org/mingw/ucrt64/mingw-w64-ucrt-x86_64-libunwind-21.1.7-1-any.pkg.tar.zst and put to /usr/x86_64-w64-mingw32ucrt/lib
linker = "x86_64-w64-mingw32ucrt-ld"
# if dynamic unwind lib is installed, the following may be needed "-Ctarget-feature=+crt-static"
rustflags = ["-Clink-arg=/usr/x86_64-w64-mingw32ucrt/lib/crt1.o", "-Clink-arg=-lmingw32", "-Clink-arg=-lmingwex", "-Clink-arg=-lucrt", "-Clink-arg=-lkernel32"] # otherwise libunwind is required at runtime
